# Generated by Django 5.0.1 on 2024-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('published', models.DateField(verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
