# Generated by Django 5.0.1 on 2024-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_readingbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingbook',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Закончена'),
        ),
    ]
