# Generated by Django 5.0.1 on 2024-02-14 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_readingbook_is_finished'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingBook',
            new_name='Printing',
        ),
    ]
